### ISSUE TITLE
Problem with generating userid: Command '['git', 'config', '--global', 'user.email']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by MrIbrahem** [gorilla-llm/gorilla-cli#16]
Unable to generate userid: Command '['git', 'config', '--global', 'user.email']' returned non-zero exit status 1.

**Comment by ShishirPatil** [comment]
Hey @MrIbrahem this should be fixed with release 0.0.9 Can you update and let me know if you still get the same error? And also do share the version no and environment, so I can replicate it locally. Thanks!

**Comment by MrIbrahem** [comment]
Thank you, looks good now. 👍 
gorilla what is my version no and environment

echo "Version: $Cuname -r), Environment: $Cuname -o)" 

Version: 4.19.0-24-cloud-amd64, Environment: GNU/Linux
