### ISSUE TITLE
Gorilla output empty when using a variable

### ISSUE THREAD

**Issue by k-bx** [gorilla-llm/gorilla-cli#19]
Raw command works while running through gorilla doesn't seem to understand the variable value:

```
$ gorilla print first 20 chars of a SCREENSHOT_B64 variable
🦍  echo $SCREENSHOT_B64 | cut -c 1-20

$ echo $SCREENSHOT_B64 | cut -c 1-20
iVBORw0KGgoAAAANSUhE
```

**Comment by ShishirPatil** [comment]
Hey @k-bx can you give me more information so I can try to recreate the issue? It seems to work on my computer ™️ 

<img width="1105" alt="image" src="https://github.com/gorilla-llm/gorilla-cli/assets/30296397/7b008330-c0a7-4d78-8a27-37d3df45c3eb">

**Comment by k-bx** [comment]
@ShishirPatil ah, I get it now. The difference between exported/non-exported variables. Not sure if it's expected or not.

<img width="463" alt="image" src="https://github.com/gorilla-llm/gorilla-cli/assets/107968/c3656d97-520f-4624-8262-e09b31acb7c6">
