### ISSUE TITLE
 gorilla help : Fails - to reach server

### ISSUE THREAD

**Issue by abhisheknist149** [gorilla-llm/gorilla-cli#20]
/ 🦍 LoadingServer is unreachable.
Try updating Gorilla-CLI with 'pip install --upgrade gorilla-cli'

It appears server is not reachable. 

Is it possible to deploy this locally on my on box and use my own keys for Models ?  @ShishirPatil

**Comment by ShishirPatil** [comment]
Hey @abhisheknist149 is this still persistent? I just checked, and all services seem to be healthy. Have you checked if your network can reach any of our end points? You can test with `ping 34.135.112.197`

**Comment by abhisheknist149** [comment]
@ShishirPatil  Thanks ping works , but command fails still - any way to troubleshoot to get more verbose...

🦍 LoadingServer is unreachable.
Try updating Gorilla-CLI with 'pip install --upgrade gorilla-cli'


Pinging 34.135.112.197 with 32 bytes of data:
Reply from 34.135.112.197: bytes=32 time=266ms TTL=43
Reply from 34.135.112.197: bytes=32 time=265ms TTL=43
Reply from 34.135.112.197: bytes=32 time=266ms TTL=43
Reply from 34.135.112.197: bytes=32 time=266ms TTL=43

Ping statistics for 34.135.112.197:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 265ms, Maximum = 266ms, Average = 265ms

**Comment by ShishirPatil** [comment]
Hmm. This is interesting. Are you behind a firewall, where any HTTP traffic might be getting dropped?

**Comment by ShishirPatil** [comment]
Closing this since I didn't hear back! Feel free to reopen.

**Comment by kordc** [comment]
I have the same problem using gorilla-cli==0.0.9 and PowerShell in Windows Terminal:
```bash
> gorilla hi
| 🦍 LoadingServer is unreachable.
Try updating Gorilla-CLI with 'pip install --upgrade gorilla-cli'

> ping 34.135.112.197

Pinging 34.135.112.197 with 32 bytes of data:
Reply from 34.135.112.197: bytes=32 time=134ms TTL=57
Reply from 34.135.112.197: bytes=32 time=134ms TTL=57
Reply from 34.135.112.197: bytes=32 time=134ms TTL=57
Reply from 34.135.112.197: bytes=32 time=134ms TTL=57

Ping statistics for 34.135.112.197:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 134ms, Maximum = 134ms, Average = 134ms
```

@ShishirPatil do you know what may cause the problem?

**Comment by whistler** [comment]
I am getting the same issue. Could this be because of an expired SSL certificate: 
```
curl https://cli.gorilla-llm.com
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by Robertullrey** [comment]
Having same issue on macOS 14.5. It seems that 34.135.112.197 can't be accessed. 

```
lynx 34.135.112.197

Looking up 34.135.112.197 first
Looking up 34.135.112.197
Making HTTP connection to 34.135.112.197
Sending HTTP request.
HTTP request sent; waiting for response.
HTTP/1.1 307 Temporary Redirect
Data transfer complete
HTTP/1.1 307 Temporary Redirect
Using https://34.135.112.197/
Looking up 34.135.112.197
Making HTTPS connection to 34.135.112.197
SSL callback:ok, preverify_ok=1, ssl_okay=0
SSL callback:ok, preverify_ok=1, ssl_okay=0
SSL callback:certificate has expired, preverify_ok=0, ssl_okay=0
SSL callback:certificate has expired, preverify_ok=1, ssl_okay=1
UNVERIFIED connection to 34.135.112.197 (cert=CN<cli.gorilla-llm.com>:SAN<DNS=cli.gorilla-l...)
Certificate issued by: /C=US/O=Let's Encrypt/CN=R3
Secure 256-bit TLSv1.3 (TLS_AES_256_GCM_SHA384) HTTP connection
Sending HTTP request.
HTTP request sent; waiting for response.
Alert!: HTTP/1.1 404 Not Found

lynx: Can't access startfile http://34.135.112.197/
```
