### ISSUE TITLE
Not compatible with Windows Terminal 

### ISSUE THREAD

**Issue by mohidmeer** [gorilla-llm/gorilla-cli#21]
![image](https://github.com/gorilla-llm/gorilla-cli/assets/48846069/248094b9-adaf-4fa2-8a4b-40b150760503)

**Comment by ShishirPatil** [comment]
Ah, thanks for trying our Gorilla-CLI and flagging this @mohidmeer The recommendations are for Gorilla through WSL (Windows subsystem for Linux) which is most usage patterns. But it should also work in your case. 
Can you try prefixing or suffixing with "windows powershell"? So in your example, the commands would be `gorilla windows powershell create a text file in current directory` or even `gorilla create a text file in current directory using windows powershell`?
