### ISSUE TITLE
Train with mpt 8k

### ISSUE THREAD

**Issue by fire** [gorilla-llm/gorilla-cli#23]
Would it be expensive to train with mpt 8k? Can you provide an mpt 8k model?

https://huggingface.co/mosaicml/mpt-7b-8k

**Comment by ShishirPatil** [comment]
Good question @fire ! MPT-7B-8k is not Apache 2.0 licensed. So, if users want to use gorilla-cli on their corporate laptops, or even build on top of Gorilla, the licensing might become tricky. We are trying to build gorilla to be 100% open sourced, that others can use freely on build on-top-of. So, no - it won't be expensive, but not clear we should do it. What do you think? 👀

**Comment by fire** [comment]
As far as I know it is apache-2 licensed. Can you check again?

**Comment by fire** [comment]
![image](https://github.com/gorilla-llm/gorilla-cli/assets/32321/e371125e-e712-404e-8aaa-c2dc03137f68)

**Comment by fire** [comment]
I'll close the issue since there was no reply.
