### ISSUE TITLE
Disable spinner.

### ISSUE THREAD

**Issue by razeta** [gorilla-llm/gorilla-cli#25]
Hello, how can I disable the spinner. I want to make a query without the loading spinner. Or where can I delete the line that adds that spinner?

**Comment by ShishirPatil** [comment]
Hey @razeta the line you want to look into is here: https://github.com/gorilla-llm/gorilla-cli/blob/a2236130bdb9f296771680e513f250ed556a2fa5/go_cli.py#L137
