### ISSUE TITLE
Problem with generating userid: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by billa0** [gorilla-llm/gorilla-cli#26]
Unable to generate userid: [WinError 2] The system cannot find the file specified

**Comment by ShishirPatil** [comment]
Hey @billa0 ! Do you happen to have `git` installed and configured? If not, you can do so with the following commands:

```bash
sudo apt install git-all # https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
git config --global user.email
rm ~/.gorilla-cli-* && pip uninstall gorilla-cli
pip install gorilla-cli
```

**Comment by billa0** [comment]
> Hey @billa0 ! Do you happen to have `git` installed and configured? If not, you can do so with the following commands:
> 
> ```shell
> sudo apt install git-all # https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
> git config --global user.email
> rm ~/.gorilla-cli-* && pip uninstall gorilla-cli
> pip install gorilla-cli
> ```

It's win 11 -

**Comment by ShishirPatil** [comment]
> It's win 11 -

Oh are you trying to use it on Windows 11 through WSL (Windows Subsystem for Linux) or through Powershell? 
I think the above set of commands works for WSL. For Powershell you just need to activate a python3 environment, and just `pip install gorilla-cli` should work out of the box 🤞 Do you mind sharing an error trace?

#21 is a good reference 👀

**Comment by ShishirPatil** [comment]
Closing this issue. Feel free to reopen it if you run into any other issues.
