### ISSUE TITLE
Could this be a use case?

### ISSUE THREAD

**Issue by netpoe** [gorilla-llm/gorilla-cli#28]
I have a NextJS project with several `.tsx` files needing translation, so: 

```
gorilla 'parse every .tsx file under ./src, extract all strings , substitute them by {t("translationKey.targetKey")} and put the strings in locales/en/translation.json'
```

Would this work? 

Otherwise, how to extend `gorilla` in order to understand and potentially accomplish this task? 

thx.

**Comment by ShishirPatil** [comment]
Hey @netpoe yes I think it should work.. Did you give it a try? Do share the results! Also, closing this issue as we can track it on Discord!
