### ISSUE TITLE
Feature Request - Generate terraform, cloudformation, etc. based on a prompt

### ISSUE THREAD

**Issue by joemccann** [gorilla-llm/gorilla-cli#29]
As a user, I'd like to prompt Gorilla with a tech stack idea on say AWS. Gorilla would reply with the code scaffolding, a GitHub repo, the code pipeline, cloud formation templates, etc.

Is this inside or outside the scope of Gorilla?

**Comment by ShishirPatil** [comment]
Oo this is actually the north star @joemccann Today, Gorilla is good at single API calls. This is definitely in the roadmap, but I suspect it will be a while before we get there 🙂
