### ISSUE TITLE
command not found: gorila

### ISSUE THREAD

**Issue by dnajd** [gorilla-llm/gorilla-cli#5]
I did the `pip install gorilla-cli` and the command is not found.  Installer is maybe not working?

```
~ $ python3 --version
Python 3.11.3

~ $ pip --version
pip 23.1.2

$ sw_vers
ProductName:		macOS
ProductVersion:		13.4.1

$ arch
arm64
```

**Comment by ShishirPatil** [comment]
Thanks for trying it out, @dnajd I think there is a misspell? It should be `gorilla` and not `gorila` (the extra `l`). Hope this fixes it.
