### ISSUE TITLE
Does internet required for tool ?

### ISSUE THREAD

**Issue by hrachstep** [gorilla-llm/gorilla-cli#55]
I tried to run gorilla in offline server wiithout internet and got 
`⠦ LoadingServer is unreachable.
Try updating Gorilla-CLI with 'pip install --upgrade gorilla-cli'`

Can you please confirm does internet required for tool? Thanks

**Comment by ShishirPatil** [comment]
Hey @hrachstep Yes, we run the inference on our hosted end-point which means you can use the tool on any machine, but it requires internet.
