### ISSUE TITLE
"LoadingServer is unreachable"

### ISSUE THREAD

**Issue by tedneward** [gorilla-llm/gorilla-cli#60]
Homebrew install (`brew install gorilla-cli`), M3 MacBook Pro running macOS 14.4.

Just installed Gorilla, then when trying to run it, I get 

```
tedneward@Teds-MBP-16 bin % gorilla say hello
⠹ LoadingServer is unreachable.
Try updating Gorilla-CLI with 'pip install --upgrade gorilla-cli'
```

But when I run pip (using `pip3` since that's what was installed with my Python, which was also Homebrew-installed), I get:

```
tedneward@Teds-MBP-16 bin % pip3 install --upgrade gorilla-cli
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a Python library that isn't in Homebrew,
    use a virtual environment:
    
    python3 -m venv path/to/venv
    source path/to/venv/bin/activate
    python3 -m pip install xyz
    
    If you wish to install a Python application that isn't in Homebrew,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. You can install pipx with
    
    brew install pipx
    
    You may restore the old behavior of pip by passing
    the '--break-system-packages' flag to pip, or by adding
    'break-system-packages = true' to your pip.conf file. The latter
    will permanently disable this error.
    
    If you disable this error, we STRONGLY recommend that you additionally
    pass the '--user' flag to pip, or set 'user = true' in your pip.conf
    file. Failure to do this can result in a broken Homebrew installation.
    
    Read more about this behavior here: <https://peps.python.org/pep-0668/>

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

Any hints or ideas what's going on in my Gorilla install?

**Comment by davidlj95** [comment]
Same here! Checkout https://github.com/ShishirPatil/gorilla/issues/436 Seems HTTPs certificate is expired

Btw seems there are 2 repos for same thing. But the one I created the issue in seems to have more recent activity. Though this one is the repo listed in PyPi's package metadata 🤔

**Comment by bdmorin** [comment]
I added `verify=False` to `/opt/homebrew/Cellar/gorilla-cli/0.0.10_1/libexec/lib/python3.12/site-packages/go_cli.py`

https://github.com/gorilla-llm/gorilla-cli/blob/6e05036417b3bfe9dcf9ad00bb670161382ddb2d/go_cli.py#L246

I do not reccomend doing this. I just wanted to see the system work.

**Comment by tedneward** [comment]
I added that to my installed copy, and it worked long enough to present me with the menu of options, then after selecting one there were all sorts of SSL errors, so I think that was my issue. I took the change back out, and I'll wait for a fix before proceeding with any further Gorilla exploration.

**Comment by ShishirPatil** [comment]
Hey Folks, thank you for raising the issue. This was indeed due to the https certificate having expired. I have renewed it now and everything should work as is. Thanks again @tedneward @davidlj95 @bdmorin for flagging this!!

**Comment by sway4em** [comment]
I'm getting the same error, I'm running it on an ARM based mac too.

**Comment by geramera1** [comment]
I hope you're good, I get the  ⠹ LoadingServer is unreachable message, running on Linux.

**Comment by larssb** [comment]
Same problem again ... @ShishirPatil any idea Sir?

**Comment by abitrolly** [comment]
Fixed again https://github.com/ShishirPatil/gorilla/issues/668#issuecomment-2418939366
