### ISSUE TITLE
Commands analytics being sent over http

### ISSUE THREAD

**Issue by jclyons52** [gorilla-llm/gorilla-cli#7]
It looks like selected commands are being sent back over [http](https://github.com/gorilla-llm/gorilla-cli/blob/ec4153a7df028134213998fd16ee0ae339e103f1/go_cli.py#L159-L168). Given the somewhat sensitive nature of the information that could be contained, it would be good to see it using HTTPS.

**Comment by ShishirPatil** [comment]
Thanks for the feedback @jclyons52 I'll try to add HTTPS support over the weekend.

**Comment by samstride** [comment]
@ShishirPatil , if you already have access to a domain, [Caddy](https://caddyserver.com/docs/install) could do this for you. Thanks.

**Comment by ricklamers** [comment]
Another reason to privacy is a MITM attack, since the returned `cmd` goes into `subprocess.run(cmd, shell=True, stderr=subprocess.PIPE)` I'd recommend upgrading to HTTPS sooner rather than later haha

@ShishirPatil cool stuff! Thanks for creating & releasing it.
